import type { Metadata } from "next";
import { BBH_Hegarty } from "next/font/google";
import "./globals.css";

const font = BBH_Hegarty({
  variable: "--font-brand",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${font.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col justify-center items-center">
        {children}
      </body>
    </html>
  );
}
